### PR TITLE
Update subnet openflow rules in case of host ip change

### PR DESCRIPTION
**Pull request by pravisankar**
Replace 'minion' with 'node' or 'nodeIP' based on context

### CODE REVIEW

**Comment by pravisankar** [comment]
Pending: Changes in  vagrant-plugin-migrate.sh  needs corresponding change in openshift/origin repo.
I'm currently testing these changes...
@rajatchopra PTAL

**Comment by pravisankar** [comment]
Fixes https://github.com/openshift/openshift-sdn/issues/116

**Comment by pravisankar** [comment]
@rajatchopra Updated and tested the changes, please review/merge

**Comment by dcbw** [comment]
Ah I see what you did here, maybe this PR should also reference https://github.com/rajatchopra/origin/pull/4 just to complete the story.

**Comment by pravisankar** [comment]
Updated PR: https://github.com/openshift/openshift-sdn/pull/119

**Pull request closed without merging**
